language: android
jdk: oraclejdk7
# Turn off caching to avoid any caching problems
cache: false
# Use the Travis Container-Based Infrastructure
sudo: false
env:
  global:
    - ANDROID_API_LEVEL=23
    - ANDROID_BUILD_TOOLS_VERSION=23.0.3
    - ANDROID_ABI=armeabi-v7a
    - ADB_INSTALL_TIMEOUT=10 # minutes (2 minutes by default)

android:
  components:
   - tools
   - build-tools-$ANDROID_BUILD_TOOLS_VERSION
   - android-$ANDROID_API_LEVEL
   - extra-android-m2repository
   # Support library
   - extra-android-support
   # Specify at least one system image
   - sys-img-armeabi-v7a-android-$ANDROID_API_LEVEL

# before_script:
  # Create emulator
  # - echo no | android create avd --force -n test -t android-$ANDROID_API_LEVEL --abi $ANDROID_ABI
  # Start emulator
  # - emulator -avd test -no-skin -no-audio -no-window &
  # - adb wait-for-device
  # inject Falcon dependency (to take screenshots)
  # - sed -i "s/^dependencies {/dependencies { compile 'com.jraska:falcon:1.0.1'/g" build.gradle
  # - sed -i "s/^repositories {/repositories { jcenter()/g" build.gradle

script:
  # Build the app
  - chmod +x gradlew
  - ./gradlew build
  # Go to About activity
  # - adb shell input tap 500 1300


# gitter integration
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/78e5e3847120190ddae2
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
