language: android
jdk: oraclejdk7
android:
  components:
   - tools
   - build-tools-23.0.2
   - android-23
   - extra-android-m2repository
   - extra-android-support

script:
  - chmod +x gradlew
  - ./gradlew check -PdisablePreDex --continue --stacktrace
  - ./gradlew assembleDebug -PdisablePreDex
  - ./gradlew assembleAndroidTest -PdisablePreDex
  - ./gradlew connectedAndroidTest
