language: android
jdk: oraclejdk7
android:
  components:
   - sys-img-armeabi-v7a-android-23
   - tools
   - build-tools-23.0.3
   - android-23
   - extra-android-m2repository
   - extra-android-support

#before_script:
  # Create and start emulator
  # - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  # - emulator -avd test -no-skin -no-audio -no-window &
  # - adb wait-for-device
  # - adb shell input keyevent 82 &

script:
  - chmod +x gradlew
  - ./gradlew check -PdisablePreDex --continue --stacktrace
  - ./gradlew assembleDebug -PdisablePreDex
  - ./gradlew assembleAndroidTest -PdisablePreDex
  - ./gradlew connectedAndroidTest

# gitter integration
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/78e5e3847120190ddae2
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
