language: android
jdk: oraclejdk7
android:
  components:
   - tools
   - build-tools-23.0.2
   - android-23
   - extra-android-m2repository
   - extra-android-support

script:
  - chmod +x gradlew
  - ./gradlew check -PdisablePreDex --continue --stacktrace
  - ./gradlew assembleDebug -PdisablePreDex
  - ./gradlew assembleAndroidTest -PdisablePreDex
  - ./gradlew connectedAndroidTest

# gitter notif
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/78e5e3847120190ddae2
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
